name: custom_math_keyboard
description: >-2
  Math expression editing using an on-screen software keyboard or physical keyboard input in a
  typeset input field in Flutter.
version: 0.2.0
repository: https://github.com/Infinitix-LLC/custom_math_keyboard.git

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_math_fork: ^0.7.1
  holding_gesture: ^1.1.0
  intl: ^0.18.0
  math_expressions: ^2.1.0
  petitparser: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.0

flutter:
  fonts:
  - family: CustomKeyIcons
    fonts:
    - asset: fonts/CustomKeyIcons.ttf
  - family: OpenSans
    fonts:
    - asset: fonts/OpenSans-Regular.ttf
